<?php

namespace App\Providers;

use App\Services\Detect\Detect;
use App\Services\Detect\Location;
use GuzzleHttp\Client;
use Laravel\Lumen\Providers\EventServiceProvider as ServiceProvider;

class DetectServiceProvider extends ServiceProvider
{
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function register()
    {
        $this->app->bind('detect',static function() {
            return new Detect(new Location(new Client()));
        });
    }
}
